tasks:
  - func: "./producer-wilkins.so"
    nprocs: 1
    outports:
      - filename: "output.nc"
        dsets:
          - name: "*"
            passthru: 1
            metadata: 0
  - func: "./consumer-wilkins.so"
    nprocs: 1
    inports:
      - filename: "output.nc"
        dsets:
          - name: "*"
            passthru: 1
            metadata: 0
