tasks:
  - func: "./producer.py"
    nprocs: 1
    actions: ["actions", "prod_callback"]
    outports:
      - filename: "output.nc"
        dsets:
          - name: "*"
            passthru: 1
            metadata: 0
  - func: "./consumer.py"
    nprocs: 1
    actions: ["actions", "con_callback"]
    inports:
      - filename: "output.nc"
        dsets:
          - name: "*"
            passthru: 1
            metadata: 0
